#!/bin/sh

# Build in builddir-pip, so we can assume that we will only find 1 .whl
python3 -mpip wheel -w builddir-pip . && \
(pip3 install --force-reinstall $(ls -t builddir-pip/pycsh*.whl | head -n 1) --break-system-packages || pip3 install --force-reinstall $(ls -t builddir-pip/pycsh*.whl | head -n 1))
